### ISSUE TITLE
groupsのソートと、ヒートマップのラベル位置のズレ

### ISSUE THREAD

**Issue by hmatsu1226** [yuifu/millefy#1]
groupsはアルファベット順に自動でソートされ可視化されるが、他の規則で並べたい場合もある。
その場合、事前にユーザーが自身でソートしていることを想定し、新たにソートしないオプションがほしい。

また、ソートされると、ヒートマップ横のラベルの位置がずれたり、組成がおかしくなる。
groupsとgroup_colorsはソートされるが、groupsに所属される数などの計算はソートされる前のもので計算されているかも？

**Comment by yuifu** [comment]
Solved in version 0.1.7.
